#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# https://www.exploit-db.com/exploits/42194/
#
beef:
    module:
        utstarcom_wa3002g4_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "UTstarcom WA3002G4 DNS Hijack"
            description: "Attempts to change the DNS setting on a UTstarcom WA3002G4 router.<br/><br/>This router reportedly does not require authentication to change the DNS servers.<br/><br/>This module has not been tested."
            authors: ["Todor Donev"]
            target:
                unknown: ["ALL"]
