#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        dns:
            enable: false
            name: 'DNS Server'
            authors: ['soh_cah_toa']
            address: '127.0.0.1'
            port: 5300
            upstream:
                [['tcp', '8.8.8.8', 53], ['udp', '8.8.8.8', 53]]
