#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        link_rewrite:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Link Rewrite"
            description: "This module will rewrite all the href attributes of all matched links."
            authors: ["passbe"]
            target:
                working: ["ALL"]
