server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 8.1 Chrome 75"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "75.0"
    "os": "windows"
    "os_version": "8.1"