#
# Copyright (c) 2006-2014 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Shell_shocked:
            enable: true
            category: "Exploits"
            name: "Shell Shock"
            description: "Attempt to use vulnerability CVE-2014-627 to execute arbitrary code. The default command attempts to get a reverse shell.<br/>Note: Set the LHOST and LPORT."
            target:
                working: ["All"]
