#
# Copyright (c) 2006-2014 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        apache_felix_remote_shell:
            enable: true
            category: "Exploits"
            name: "Apache Felix Remote Shell (Reverse Shell)"
            description: "This module attempts to get a reverse shell on an Apache Felix Remote Shell server using the 'exec' command. The org.eclipse.osgi and org.eclipse.equinox.console bundles must be installed and active."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
