#
# Copyright (c) 2006-2015 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        firefox_extension_dropper:
            enable: true
            category: ["Social Engineering"]
            name: "Firefox Extension (Dropper)"
            description: "Create on the fly a malicious Firefox extension that embeds a dropper you can specify (add it to the 'dropper' directory). <br/><br/> The extension is based on the original work from Michael Schierl and his Metasploit module."
            authors: ["antisnatchor"]
            target:
                user_notify: ["FF"]
                not_working: ["All"]
