#
# Copyright (c) 2006-2015 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        jenkins_groovy_code_exec:
            enable: true
            category: "Exploits"
            name: "Jenkins Code Exec CSRF"
            description: "This module attempts to get a reverse shell from Jenkins web interface Groovy Script console. Works if the user is authenticated with console privileges or authentication is disabled."
            authors: ["Vadodil Joel Varghese", "OSVDB-110820", "bcoles"]
            target:
                working: ["ALL"]
