#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_page_links:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Get Page HREFs"
            description: "This module will retrieve HREFs from the target page."
            authors: ["vo"]
            target:
                working: ["ALL"]
