#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# http://www.exploit-db.com/exploits/35917/
#
beef:
    module:
        dlink_dsl2740r_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "D-Link DSL-2740R DNS Hijack"
            description: "Attempts to change the DNS setting on D-Link DSL-2740R routers.<br/><br/>D-Link DSL-2740R routers reportedly do not require authentication to change the DNS servers.<br/><br/>This module has not been tested."
            authors: ["Todor Donev"]
            target:
                unknown: ["ALL"]
