#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap
#
beef:
    module:
        phonegap_detect:
            enable: true
            category: "Phonegap"
            name: "Detect PhoneGap"
            description: "Detects if the PhoneGap API is present."
            authors: ["mh"]
            target:
                working: ["All"]
