#
beef:
    module:
        farsite_X25_remote_shell:
            enable: true
            category: "Exploits"
            name: "Farsite X25 gateway remote code execution"
            description: "This module exploits CVE-2014- to write a payload to the router and CVE-2014- to execute it. Once you have shell you can use the setuid /http/bin/execCmd to execute commands as root."
            authors: ["Wireghoul"]
            target:
                working: ["All"]

