#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_internal_ip:
            enable: true
            category: "Host"
            name: "Get Internal IP (Java)"
            description: "Retrieve the internal (behind NAT) IP address of the victim machine using an unsigned Java applet.<br/><br/>The browser must have Java enabled and configured to allow execution of unsigned Java applets."
            authors: ["antisnatchor"]
            target:
                 user_notify: ["ALL"]
