#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_ntop_network_hosts:
            enable: true
            category: "Network"
            name: "Get ntop Network Hosts"
            description: "This module retrieves network information from ntop (unauthenticated).<br/><br/>Tested on:<ul><li>ntop v.5.0.1 on Ubuntu 14.04.1 Server (x86_64)</li><li>ntop v.5.0 on Fedora 19.1 (x86_64)</li><li>ntop v.4.1.0 on Solaris 11.1 (x86)</li></ul><br/>This module does not work for ntop-ng."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
