#
# Copyright (c) 2006-2018 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap
#
beef:
    module:
        phonegap_check_connection:
            enable: true
            category: "Phonegap"
            name: "Check Connection"
            description: "Find out the network connection type e.g. Wifi, 3G. This module requires the PhoneGap API."
            authors: ["mh"]
            target:
                working: ["All"]
