#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        netgear_dgn2200_cmd_exec:
            enable: true
            category: ["Exploits", "Router"]
            name: "Netgear DGN2200 Command Execution"
            description: "This module exploits <a href='http://securitygodmode.blogspot.com/2016/02/netgears-dgn2200-multiple.html'>authentication bypass and command execution vulnerabilities</a> to execute arbitrary commands on Netgear DGN2200 routers."
            authors: ["0x3d5157636b525761", "bcoles"]
            target:
                working: ["ALL"]
