#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        unhook:
            enable: true
            category: "Browser"
            name: "Unhook"
            description: "This module removes the BeEF hook from the hooked page."
            authors: ["bcoles"]
            target:
                 working: ["All"]
