#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        linksys_e2500_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "Linksys E2500 CSRF"
            description: "Attempts to enable remote administration and change the password on a Linksys E2500 router."
            authors: ["Esteban Rodriguez"]
            target:
                working: ["ALL"]
