#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# https://www.exploit-db.com/exploits/40901/
#
beef:
    module:
        argw4_adsl_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "ARG-W4 ADSL Router DNS Hijack CSRF"
            description: "Attempts to change the DNS setting on a ARG-W4 ADSL router.<br/><br/>This module has not been tested."
            authors: ["Mojtaba MobhaM"]
            target:
                unknown: ["ALL"]
