#
# Copyright (c) 2006-2014 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        firefox_extension_reverse_shell:
            enable: true
            category: ["Exploits", "Local Host"]
            name: "Firefox Extension (Reverse Shell)"
            description: "Create on the fly a malicious Firefox extension that makes a reverse shell connection to a specified host:port.<br/><br/>The extension is based on the original work from Michael Schierl and his Metasploit module, and joev's Firefox payloads for Metasploit."
            authors: ["antisnatchor", "bcoles"]
            target:
                user_notify: ["FF"]
                not_working: ["All"]
