#
# Copyright (c) 2006-2013 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Active_fax_beef_bind:
            enable: true
            category: ["Exploits", "BeEF_bind"]
            name: "Active Fax 5.01"
            description: "This module attempts to exploit ActiveFax Server 5.01. The bug was initially discovered by Craig Freyman (for more information refer to: <a href='http://www.pwnag3.com/2013/02/actfax-raw-server-exploit.html'>http://www.pwnag3.com/2013/02/actfax-raw-server-exploit.html</a>).  His initial exploit has been modified in order to deliver the BeEF bind payload through Inter-Protocol Exploitation (IPE)."
            authors: ["antisnatchor","Bart Leppens"]
            target:
                working: ["FF"]
