#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_autocomplete_creds:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Get Autocomplete Credentials"
            description: "This module steals saved credentials for the hooked origin.<br/><br/>Tested on Firefox 68 and Chrome 49.<br/><br/>Note: On Firefox, the window must have focus."
            authors: ["bcoles"]
            target:
                working: ["FF", "C"]
                not_working: ["ALL"]
