#
# Copyright (c) 2006-2018 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   Phonegap_prompt_user
#
beef:
    module:
        phonegap_prompt_user:
            enable: true
            category: "Phonegap"
            name: "Prompt User"
            description: "Ask device user a question. This module requires the PhoneGap API."
            authors: ["staregate"]
            target:
                working: ["All"]
