#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        ddwrt_v24_sp1_cmd_exec:
            enable: true
            category: ['Exploits', 'Router']
            name: 'DD-WRT v24 SP1 Command Execution'
            description: 'DD-WRT v24 SP1 fails to properly handle metacharacters in the
                HTTP management interface. This module abuses that flaw by injecting
                metacharacters to allow an unauthenticated attacker to execute arbitrary
                commands as the root user.'
            authors: ['soh_cah_toa']
            target:
                working: ['ALL']
