#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        alert_dialog:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Create Alert Dialog"
            description: "Sends an alert dialog to the hooked browser."
            authors: ["wade", "bm"]
            target:
                user_notify: ["All"]
