#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Dlink_dgs_1100_port_mirroring_csrf:
            enable: true
            category: ["Exploits", "Switch"]
            name: "DLINK DGS 1100-08 Port Mirroring CSRF"
            description: "Enables port mirroring on a specified switch port"
            authors: ["Nick Starke"]
            target:
                working: ["ALL"]
