#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Netgear_dgn_2000_wan_mgmt_csrf:
            enable: true
            category: [ "Exploits", "Router" ]
            name: "Netgear DGN 2000 WAN Remote Management"
            description: "Attempts to enable remote management of the router on the WAN"
            authors: ["Nick Starke"]
            target:
                working: ["ALL"]
