#
# Copyright (c) 2006-2018 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap
#
beef:
    module:
        phonegap_beep:
            enable: true
            category: "Phonegap"
            name: "Beep"
            description: "Make the phone beep. This module requires the PhoneGap API."
            authors: ["mh"]
            target:
                working: ["All"]
