#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap persistence
#
beef:
    module:
        phonegap_persistence:
            enable: true
            category: "Phonegap"
            name: "Persistence (PhoneGap)"
            description: "Insert the BeEF hook into PhoneGap's index.html (iPhone only). This module requires the PhoneGap API."
            authors: ["mh"]
            target:
                working: ["All"]
