#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        bozo_crack:
            enable: true
            category: "Misc"
            name: "BozoCrack"
            description: "This module uses the hooked browser to crack MD5 hashes using Google. It borrows from the <a href='https://github.com/juuso/BozoCrack' target='_blank'>BozoCrack</a> tool by juuso."
            authors: ["juuso", "bcoles"]
            target:
                working: ["ALL"]
