#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Detect_toolbars:
            enable: true
            category: "Browser"
            name: "Detect Toolbars"
            description: "Detects which browser toolbars are installed."
            authors: ["gcattani"]
            target:
                working: ["All"]
