#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        Dlink_dgs_1100_device_reset_csrf:
            enable: true
            category: ["Exploits", "Switch"]
            name: "DLINK DGS 1100-08 Device Reset CSRF"
            description: "Reset's everything on the device except for the IP address.  Default password is 'admin'"
            authors: ["Nick Starke"]
            target:
                working: ["ALL"]
