#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        proxy:
            name: 'Proxy'
            enable: false
            address: "127.0.0.1"
            port: 6789
            authors: ["antisnatchor", "scotty"]
            key: "beef_key.pem"
            cert: "beef_cert.pem"
