#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_soc_nets:
            enable: true
            category: "Network"
            name: "Detect Social Networks"
            description: "This module will detect if the Hooked Browser is currently authenticated to GMail, Facebook and Twitter."
            authors: ["xntrik", "Mike Cardwell"]
            target:
                working: ["ALL"]
