#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        site_redirect:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Redirect Browser (Standard)"
            description: "This module will redirect the selected hooked browser to the address specified in the 'Redirect URL' input."
            authors: ["wade", "vo"]
            target:
                user_notify: ["ALL"]
