#
# Copyright (c) 2006-2015 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        asus_rt_n12e_get_info:
            enable: true
            category: ["Exploits", "Router"]
            name: "Asus RT-N12E Get Info"
            description: "This module retrieves network information from Asus RT-N12E routers, including WAN link details (WAN IP address, gateway, DNS server) and the MAC address and IP address of all connected clients.<br/>Tested on Firmware version 2.0.0.35."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
