#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_office:
            enable: true
            category: "Browser"
            name: "Detect MS Office"
            description: "This module detect the version of MS Office if installed"
            authors: ["nbblrr"]
            target:
                working: ["IE"]
                not_working: ["All"]
