#
# Copyright (c) 2006-2015 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        asus_rt_series_get_info:
            enable: true
            category: ["Exploits", "Router"]
            name: "Asus RT Series Get Info"
            description: "This module retieves information from an Asus RT series router unauthenticated. The information retrieved includes all connected LAN clients (MAC address and LAN IP) and WAN link details (WAN IP address, gateway, DNS server)."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
