#
# Copyright (c) 2006-2014 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        dlink_sharecenter_cmd_exec:
            enable: true
            category: ["Exploits", "NAS"]
            name: "D-Link ShareCenter Command Execution"
            description: "Attempts to execute arbitrary commands on a D-Link ShareCenter NAS. Multiple models are affected, including DNS-320 and DNS-325, however this module has not been tested.<br/><br/>For more information see, http://blog.emaze.net/2012_02_01_archive.html"
            authors: ["bcoles", "Roberto Paleari, Emaze Networks S.p.A."]
            target:
                working: ["ALL"]
