#   phonegap
#
beef:
    module:
        Geo_locate:
            enable: true
            category: "Phonegap"
            name: "Geolocation"
            description: "Geo locate your victim."
            authors: ["mh"]
            target:
                working: ["All"]
