#
# Copyright (c) 2006-2018 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap_plugin_detection
#
beef:
    module:
        phonegap_plugin_detection:
            enable: true
            category: "Phonegap"
            name: "List Plugins"
            description: "Attempts to guess installed plugins. This module requires the PhoneGap API."
            authors: ["staregate"]
            target:
                working: ["All"]
