#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        invisible_htmlfile_activex:
            enable: true
            category: "Persistence"
            name: "Invisible HTMLFile (ActiveX)"
            description: "This module uses a <i>HTMLFile</i> ActiveX object to create an invisible HTML document containing a BeEF hook. The hook persists until the tab is closed. Internet Explorer only.<br/><br/> Based on <a href='https://www.brokenbrowser.com/zombie-alert/'>research</a> by <a href='https://twitter.com/magicmac2000'>@MagicMac2000</a>."
            authors: ["bcoles", "@MagicMac2000"]
            target:
                working:
                    IE:
                        min_ver: 11
                        max_ver: latest
                not_working: ["All"]
