#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        clipboard_theft:
            enable: true
            category: "Host"
            name: "Get Clipboard"
            description: "Retrieves the clipboard contents. This module works invisibly with Internet Explorer 6.x however Internet Explorer 7.x - 8.x will prompt the user for permission to access the clipboard."
            authors: ["bcoles"]
            target:
                working: 
                    IE:
                        min_ver: 6
                        max_ver: 6
                user_notify:
                    IE:
                        min_ver: 7
                        max_ver: 8
                not_working: ["All"]

