#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# https://www.exploit-db.com/exploits/40368/
#
beef:
    module:
        inteno_eg101r1_voip_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "Inteno EG101R1 VoIP Router DNS Hijack"
            description: "Attempts to change the DNS setting on a Inteno EG101R1 VoIP router.<br/><br/>The Inteno EG101R1 VoIP router reportedly does not require authentication to change the DNS servers.<br/><br/>This module has not been tested."
            authors: ["Todor Donev"]
            target:
                unknown: ["ALL"]
