#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        console:
            enable: true 
            name: 'Console'
            shell:
                enable: true
                historyfolder: '~/.beef/'
                historyfile: 'history'

