#
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        detect_activex:
            enable: true
            category: "Browser"
            name: "Detect ActiveX"
            description: "This module will check if the browser has ActiveX support."
            authors: ["bcoles"]
            target:
                user_notify: ["IE"]
                not_working: ["All"]
