#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        admin_ui:
            name: 'Admin UI'
            enable: false
            favicon_file_name: "favicon.ico"
            favicon_dir: "/images"
            login_fail_delay: 1
            play_sound_on_new_zombie: false

