#
# Copyright (c) 2006-2017 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        clear_console:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Clear Console"
            description: "This module clears the Chrome developer console buffer."
            authors: ["bcoles"]
            target:
                user_notify: ["C"]
                not_working: ["All"]

