name: 'BrowserStack Test'

on:
  push:
    branches: [feature/ci]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    env: 
      GITACTIONS: true
    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Setting up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2 # Not needed with a .ruby-version file

      - name: 'Build and run tests'
        run: |
          sudo apt update
          sudo apt install libcurl
          bundle config unset --local without
          bundle config set --local with 'test' 'development'
          bundle install
          bundle exec rake browserstack --trace

      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
