#
# Copyright (c) 2006-2016 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# https://www.exploit-db.com/exploits/37237/
#
beef:
    module:
        dlink_dsl2780b_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "D-Link DSL-2780B ADSL Router DNS Hijack"
            description: "Attempts to change the DNS setting on a D-Link DSL-2780B ADSL router.<br/><br/>This router reportedly does not require authentication to change the DNS servers.<br/><br/>This module has not been tested."
            authors: ["Todor Donev"]
            target:
                unknown: ["ALL"]
