#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        prompt_dialog:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Create Prompt Dialog"
            description: "Sends a prompt dialog to the hooked browser."
            authors: ["wade", "bm"]
            target:
                user_notify: ['ALL']
